// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

#ifndef POOSLTYPES_HXX
#define POOSLTYPES_HXX

#ifndef XSD_CXX11
#define XSD_CXX11
#endif

#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_TREE_USE_CHAR
#define XSD_CXX_TREE_USE_CHAR
#endif

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (XSD_INT_VERSION != 4000000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#include <xsd/cxx/xml/char-iso8859-1.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/types.hxx>

#include <xsd/cxx/xml/error-handler.hxx>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

#include <xsd/cxx/tree/parsing.hxx>
#include <xsd/cxx/tree/parsing/byte.hxx>
#include <xsd/cxx/tree/parsing/unsigned-byte.hxx>
#include <xsd/cxx/tree/parsing/short.hxx>
#include <xsd/cxx/tree/parsing/unsigned-short.hxx>
#include <xsd/cxx/tree/parsing/int.hxx>
#include <xsd/cxx/tree/parsing/unsigned-int.hxx>
#include <xsd/cxx/tree/parsing/long.hxx>
#include <xsd/cxx/tree/parsing/unsigned-long.hxx>
#include <xsd/cxx/tree/parsing/boolean.hxx>
#include <xsd/cxx/tree/parsing/float.hxx>
#include <xsd/cxx/tree/parsing/double.hxx>
#include <xsd/cxx/tree/parsing/decimal.hxx>

#include <xsd/cxx/xml/dom/serialization-header.hxx>
#include <xsd/cxx/tree/serialization.hxx>
#include <xsd/cxx/tree/serialization/byte.hxx>
#include <xsd/cxx/tree/serialization/unsigned-byte.hxx>
#include <xsd/cxx/tree/serialization/short.hxx>
#include <xsd/cxx/tree/serialization/unsigned-short.hxx>
#include <xsd/cxx/tree/serialization/int.hxx>
#include <xsd/cxx/tree/serialization/unsigned-int.hxx>
#include <xsd/cxx/tree/serialization/long.hxx>
#include <xsd/cxx/tree/serialization/unsigned-long.hxx>
#include <xsd/cxx/tree/serialization/boolean.hxx>
#include <xsd/cxx/tree/serialization/float.hxx>
#include <xsd/cxx/tree/serialization/double.hxx>
#include <xsd/cxx/tree/serialization/decimal.hxx>

#include <xsd/cxx/tree/std-ostream-operators.hxx>

namespace xml_schema
{
  // anyType and anySimpleType.
  //
  typedef ::xsd::cxx::tree::type Type;
  typedef ::xsd::cxx::tree::simple_type< char, Type > SimpleType;
  typedef ::xsd::cxx::tree::type Container;

  // 8-bit
  //
  typedef signed char Byte;
  typedef unsigned char UnsignedByte;

  // 16-bit
  //
  typedef short Short;
  typedef unsigned short UnsignedShort;

  // 32-bit
  //
  typedef int Int;
  typedef unsigned int UnsignedInt;

  // 64-bit
  //
  typedef long long Long;
  typedef unsigned long long UnsignedLong;

  // Supposed to be arbitrary-length integral types.
  //
  typedef long long Integer;
  typedef long long NonPositiveInteger;
  typedef unsigned long long NonNegativeInteger;
  typedef unsigned long long PositiveInteger;
  typedef long long NegativeInteger;

  // Boolean.
  //
  typedef bool Boolean;

  // Floating-point types.
  //
  typedef float Float;
  typedef double Double;
  typedef double Decimal;

  // String types.
  //
  typedef ::xsd::cxx::tree::string< char, SimpleType > String;
  typedef ::xsd::cxx::tree::normalized_string< char, String > NormalizedString;
  typedef ::xsd::cxx::tree::token< char, NormalizedString > Token;
  typedef ::xsd::cxx::tree::name< char, Token > Name;
  typedef ::xsd::cxx::tree::nmtoken< char, Token > Nmtoken;
  typedef ::xsd::cxx::tree::nmtokens< char, SimpleType, Nmtoken > Nmtokens;
  typedef ::xsd::cxx::tree::ncname< char, Name > Ncname;
  typedef ::xsd::cxx::tree::language< char, Token > Language;

  // ID/IDREF.
  //
  typedef ::xsd::cxx::tree::id< char, Ncname > Id;
  typedef ::xsd::cxx::tree::idref< char, Ncname, Type > Idref;
  typedef ::xsd::cxx::tree::idrefs< char, SimpleType, Idref > Idrefs;

  // URI.
  //
  typedef ::xsd::cxx::tree::uri< char, SimpleType > Uri;

  // Qualified name.
  //
  typedef ::xsd::cxx::tree::qname< char, SimpleType, Uri, Ncname > Qname;

  // Binary.
  //
  typedef ::xsd::cxx::tree::buffer< char > Buffer;
  typedef ::xsd::cxx::tree::base64_binary< char, SimpleType > Base64Binary;
  typedef ::xsd::cxx::tree::hex_binary< char, SimpleType > HexBinary;

  // Date/time.
  //
  typedef ::xsd::cxx::tree::time_zone TimeZone;
  typedef ::xsd::cxx::tree::date< char, SimpleType > Date;
  typedef ::xsd::cxx::tree::date_time< char, SimpleType > DateTime;
  typedef ::xsd::cxx::tree::duration< char, SimpleType > Duration;
  typedef ::xsd::cxx::tree::gday< char, SimpleType > Gday;
  typedef ::xsd::cxx::tree::gmonth< char, SimpleType > Gmonth;
  typedef ::xsd::cxx::tree::gmonth_day< char, SimpleType > GmonthDay;
  typedef ::xsd::cxx::tree::gyear< char, SimpleType > Gyear;
  typedef ::xsd::cxx::tree::gyear_month< char, SimpleType > GyearMonth;
  typedef ::xsd::cxx::tree::time< char, SimpleType > Time;

  // Entity.
  //
  typedef ::xsd::cxx::tree::entity< char, Ncname > Entity;
  typedef ::xsd::cxx::tree::entities< char, SimpleType, Entity > Entities;

  typedef ::xsd::cxx::tree::content_order ContentOrder;
  // Namespace information and list stream. Used in
  // serialization functions.
  //
  typedef ::xsd::cxx::xml::dom::namespace_info< char > NamespaceInfo;
  typedef ::xsd::cxx::xml::dom::namespace_infomap< char > NamespaceInfomap;
  typedef ::xsd::cxx::tree::list_stream< char > ListStream;
  typedef ::xsd::cxx::tree::as_double< Double > AsDouble;
  typedef ::xsd::cxx::tree::as_decimal< Decimal > AsDecimal;
  typedef ::xsd::cxx::tree::facet Facet;

  // Flags and properties.
  //
  typedef ::xsd::cxx::tree::flags Flags;
  typedef ::xsd::cxx::tree::properties< char > Properties;

  // Parsing/serialization diagnostics.
  //
  typedef ::xsd::cxx::tree::severity Severity;
  typedef ::xsd::cxx::tree::error< char > Error;
  typedef ::xsd::cxx::tree::diagnostics< char > Diagnostics;

  // Exceptions.
  //
  typedef ::xsd::cxx::tree::exception< char > Exception;
  typedef ::xsd::cxx::tree::bounds< char > Bounds;
  typedef ::xsd::cxx::tree::duplicate_id< char > DuplicateId;
  typedef ::xsd::cxx::tree::parsing< char > Parsing;
  typedef ::xsd::cxx::tree::expected_element< char > ExpectedElement;
  typedef ::xsd::cxx::tree::unexpected_element< char > UnexpectedElement;
  typedef ::xsd::cxx::tree::expected_attribute< char > ExpectedAttribute;
  typedef ::xsd::cxx::tree::unexpected_enumerator< char > UnexpectedEnumerator;
  typedef ::xsd::cxx::tree::expected_text_content< char > ExpectedTextContent;
  typedef ::xsd::cxx::tree::no_prefix_mapping< char > NoPrefixMapping;
  typedef ::xsd::cxx::tree::no_type_info< char > NoTypeInfo;
  typedef ::xsd::cxx::tree::not_derived< char > NotDerived;
  typedef ::xsd::cxx::tree::serialization< char > Serialization;

  // Error handler callback interface.
  //
  typedef ::xsd::cxx::xml::error_handler< char > ErrorHandler;

  // DOM interaction.
  //
  namespace dom
  {
    // Automatic pointer for DOMDocument.
    //
    using ::xsd::cxx::xml::dom::unique_ptr;

#ifndef XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
#define XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
    // DOM user data key for back pointers to tree nodes.
    //
    const XMLCh* const treeNodeKey = ::xsd::cxx::tree::user_data_keys::node;
#endif
  }
}

// Forward declarations.
//
namespace poosl
{
  class T_message_type;
  class T_boolean;
  class T_typed_variable;
  class T_poosl_type_attribute;
  class T_identifier;
  class T_class_name;
  class T_poosl_type;
  class T_port_name;
  class T_variable_name;
  class T_message_name;
  class T_method_name;
  class T_data_method_name;
  class T_operator;
  class T_empty;
}


#include <memory>    // ::std::unique_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search
#include <utility>   // std::move

#include <xsd/cxx/xml/char-iso8859-1.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include <xsd/cxx/tree/containers-wildcard.hxx>

namespace poosl
{
  class T_message_type: public ::xml_schema::String
  {
    public:
    enum Value
    {
      read,
      write
    };

    T_message_type ();

    T_message_type (Value v);

    T_message_type (const char* v);

    T_message_type (const ::std::string& v);

    T_message_type (const ::xml_schema::String& v);

    T_message_type (const ::xercesc::DOMElement& e,
                    ::xml_schema::Flags f = 0,
                    ::xml_schema::Container* c = 0);

    T_message_type (const ::xercesc::DOMAttr& a,
                    ::xml_schema::Flags f = 0,
                    ::xml_schema::Container* c = 0);

    T_message_type (const ::std::string& s,
                    const ::xercesc::DOMElement* e,
                    ::xml_schema::Flags f = 0,
                    ::xml_schema::Container* c = 0);

    T_message_type (const T_message_type& x,
                    ::xml_schema::Flags f = 0,
                    ::xml_schema::Container* c = 0);

    virtual T_message_type*
    _clone (::xml_schema::Flags f = 0,
            ::xml_schema::Container* c = 0) const;

    T_message_type&
    operator= (Value v);

    virtual
    operator Value () const
    {
      return _xsd_T_message_type_convert ();
    }

    protected:
    Value
    _xsd_T_message_type_convert () const;

    public:
    static const char* const _xsd_T_message_type_literals_[2];
    static const Value _xsd_T_message_type_indexes_[2];
  };

  class T_boolean: public ::xml_schema::String
  {
    public:
    enum Value
    {
      true_,
      false_
    };

    T_boolean ();

    T_boolean (Value v);

    T_boolean (const char* v);

    T_boolean (const ::std::string& v);

    T_boolean (const ::xml_schema::String& v);

    T_boolean (const ::xercesc::DOMElement& e,
               ::xml_schema::Flags f = 0,
               ::xml_schema::Container* c = 0);

    T_boolean (const ::xercesc::DOMAttr& a,
               ::xml_schema::Flags f = 0,
               ::xml_schema::Container* c = 0);

    T_boolean (const ::std::string& s,
               const ::xercesc::DOMElement* e,
               ::xml_schema::Flags f = 0,
               ::xml_schema::Container* c = 0);

    T_boolean (const T_boolean& x,
               ::xml_schema::Flags f = 0,
               ::xml_schema::Container* c = 0);

    virtual T_boolean*
    _clone (::xml_schema::Flags f = 0,
            ::xml_schema::Container* c = 0) const;

    T_boolean&
    operator= (Value v);

    virtual
    operator Value () const
    {
      return _xsd_T_boolean_convert ();
    }

    protected:
    Value
    _xsd_T_boolean_convert () const;

    public:
    static const char* const _xsd_T_boolean_literals_[2];
    static const Value _xsd_T_boolean_indexes_[2];
  };

  class T_typed_variable: public ::xml_schema::Type
  {
    public:
    // name
    //
    typedef ::poosl::T_variable_name NameType;
    typedef ::xsd::cxx::tree::traits< NameType, char > NameTraits;

    const NameType&
    getName () const;

    NameType&
    getName ();

    void
    setName (const NameType& x);

    void
    setName (::std::unique_ptr< NameType > p);

    // type
    //
    typedef ::poosl::T_poosl_type TypeType;
    typedef ::xsd::cxx::tree::traits< TypeType, char > TypeTraits;

    const TypeType&
    getType () const;

    TypeType&
    getType ();

    void
    setType (const TypeType& x);

    void
    setType (::std::unique_ptr< TypeType > p);

    // Constructors.
    //
    T_typed_variable ();

    T_typed_variable (const NameType&,
                      const TypeType&);

    T_typed_variable (const ::xercesc::DOMElement& e,
                      ::xml_schema::Flags f = 0,
                      ::xml_schema::Container* c = 0);

    T_typed_variable (const T_typed_variable& x,
                      ::xml_schema::Flags f = 0,
                      ::xml_schema::Container* c = 0);

    virtual T_typed_variable*
    _clone (::xml_schema::Flags f = 0,
            ::xml_schema::Container* c = 0) const;

    T_typed_variable&
    operator= (const T_typed_variable& x);

    virtual 
    ~T_typed_variable ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::Flags);

    protected:
    ::xsd::cxx::tree::one< NameType > name_;
    ::xsd::cxx::tree::one< TypeType > type_;
  };

  class T_poosl_type_attribute: public ::xml_schema::Type
  {
    public:
    // type
    //
    typedef ::poosl::T_poosl_type TypeType;
    typedef ::xsd::cxx::tree::traits< TypeType, char > TypeTraits;

    const TypeType&
    getType () const;

    TypeType&
    getType ();

    void
    setType (const TypeType& x);

    void
    setType (::std::unique_ptr< TypeType > p);

    // Constructors.
    //
    T_poosl_type_attribute ();

    T_poosl_type_attribute (const TypeType&);

    T_poosl_type_attribute (const ::xercesc::DOMElement& e,
                            ::xml_schema::Flags f = 0,
                            ::xml_schema::Container* c = 0);

    T_poosl_type_attribute (const T_poosl_type_attribute& x,
                            ::xml_schema::Flags f = 0,
                            ::xml_schema::Container* c = 0);

    virtual T_poosl_type_attribute*
    _clone (::xml_schema::Flags f = 0,
            ::xml_schema::Container* c = 0) const;

    T_poosl_type_attribute&
    operator= (const T_poosl_type_attribute& x);

    virtual 
    ~T_poosl_type_attribute ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::Flags);

    protected:
    ::xsd::cxx::tree::one< TypeType > type_;
  };

  class T_identifier: public ::xml_schema::String
  {
    public:
    // Constructors.
    //
    T_identifier ();

    T_identifier (const char*);

    T_identifier (const ::std::string&);

    T_identifier (const ::xml_schema::String&);

    T_identifier (const ::xercesc::DOMElement& e,
                  ::xml_schema::Flags f = 0,
                  ::xml_schema::Container* c = 0);

    T_identifier (const ::xercesc::DOMAttr& a,
                  ::xml_schema::Flags f = 0,
                  ::xml_schema::Container* c = 0);

    T_identifier (const ::std::string& s,
                  const ::xercesc::DOMElement* e,
                  ::xml_schema::Flags f = 0,
                  ::xml_schema::Container* c = 0);

    T_identifier (const T_identifier& x,
                  ::xml_schema::Flags f = 0,
                  ::xml_schema::Container* c = 0);

    virtual T_identifier*
    _clone (::xml_schema::Flags f = 0,
            ::xml_schema::Container* c = 0) const;

    virtual 
    ~T_identifier ();
  };

  class T_class_name: public ::poosl::T_identifier
  {
    public:
    // Constructors.
    //
    T_class_name ();

    T_class_name (const char*);

    T_class_name (const ::std::string&);

    T_class_name (const ::xml_schema::String&);

    T_class_name (const ::xercesc::DOMElement& e,
                  ::xml_schema::Flags f = 0,
                  ::xml_schema::Container* c = 0);

    T_class_name (const ::xercesc::DOMAttr& a,
                  ::xml_schema::Flags f = 0,
                  ::xml_schema::Container* c = 0);

    T_class_name (const ::std::string& s,
                  const ::xercesc::DOMElement* e,
                  ::xml_schema::Flags f = 0,
                  ::xml_schema::Container* c = 0);

    T_class_name (const T_class_name& x,
                  ::xml_schema::Flags f = 0,
                  ::xml_schema::Container* c = 0);

    virtual T_class_name*
    _clone (::xml_schema::Flags f = 0,
            ::xml_schema::Container* c = 0) const;

    virtual 
    ~T_class_name ();
  };

  class T_poosl_type: public ::poosl::T_class_name
  {
    public:
    // Constructors.
    //
    T_poosl_type ();

    T_poosl_type (const char*);

    T_poosl_type (const ::std::string&);

    T_poosl_type (const ::xml_schema::String&);

    T_poosl_type (const ::xercesc::DOMElement& e,
                  ::xml_schema::Flags f = 0,
                  ::xml_schema::Container* c = 0);

    T_poosl_type (const ::xercesc::DOMAttr& a,
                  ::xml_schema::Flags f = 0,
                  ::xml_schema::Container* c = 0);

    T_poosl_type (const ::std::string& s,
                  const ::xercesc::DOMElement* e,
                  ::xml_schema::Flags f = 0,
                  ::xml_schema::Container* c = 0);

    T_poosl_type (const T_poosl_type& x,
                  ::xml_schema::Flags f = 0,
                  ::xml_schema::Container* c = 0);

    virtual T_poosl_type*
    _clone (::xml_schema::Flags f = 0,
            ::xml_schema::Container* c = 0) const;

    virtual 
    ~T_poosl_type ();
  };

  class T_port_name: public ::poosl::T_identifier
  {
    public:
    // Constructors.
    //
    T_port_name ();

    T_port_name (const char*);

    T_port_name (const ::std::string&);

    T_port_name (const ::xml_schema::String&);

    T_port_name (const ::xercesc::DOMElement& e,
                 ::xml_schema::Flags f = 0,
                 ::xml_schema::Container* c = 0);

    T_port_name (const ::xercesc::DOMAttr& a,
                 ::xml_schema::Flags f = 0,
                 ::xml_schema::Container* c = 0);

    T_port_name (const ::std::string& s,
                 const ::xercesc::DOMElement* e,
                 ::xml_schema::Flags f = 0,
                 ::xml_schema::Container* c = 0);

    T_port_name (const T_port_name& x,
                 ::xml_schema::Flags f = 0,
                 ::xml_schema::Container* c = 0);

    virtual T_port_name*
    _clone (::xml_schema::Flags f = 0,
            ::xml_schema::Container* c = 0) const;

    virtual 
    ~T_port_name ();
  };

  class T_variable_name: public ::poosl::T_identifier
  {
    public:
    // Constructors.
    //
    T_variable_name ();

    T_variable_name (const char*);

    T_variable_name (const ::std::string&);

    T_variable_name (const ::xml_schema::String&);

    T_variable_name (const ::xercesc::DOMElement& e,
                     ::xml_schema::Flags f = 0,
                     ::xml_schema::Container* c = 0);

    T_variable_name (const ::xercesc::DOMAttr& a,
                     ::xml_schema::Flags f = 0,
                     ::xml_schema::Container* c = 0);

    T_variable_name (const ::std::string& s,
                     const ::xercesc::DOMElement* e,
                     ::xml_schema::Flags f = 0,
                     ::xml_schema::Container* c = 0);

    T_variable_name (const T_variable_name& x,
                     ::xml_schema::Flags f = 0,
                     ::xml_schema::Container* c = 0);

    virtual T_variable_name*
    _clone (::xml_schema::Flags f = 0,
            ::xml_schema::Container* c = 0) const;

    virtual 
    ~T_variable_name ();
  };

  class T_message_name: public ::poosl::T_identifier
  {
    public:
    // Constructors.
    //
    T_message_name ();

    T_message_name (const char*);

    T_message_name (const ::std::string&);

    T_message_name (const ::xml_schema::String&);

    T_message_name (const ::xercesc::DOMElement& e,
                    ::xml_schema::Flags f = 0,
                    ::xml_schema::Container* c = 0);

    T_message_name (const ::xercesc::DOMAttr& a,
                    ::xml_schema::Flags f = 0,
                    ::xml_schema::Container* c = 0);

    T_message_name (const ::std::string& s,
                    const ::xercesc::DOMElement* e,
                    ::xml_schema::Flags f = 0,
                    ::xml_schema::Container* c = 0);

    T_message_name (const T_message_name& x,
                    ::xml_schema::Flags f = 0,
                    ::xml_schema::Container* c = 0);

    virtual T_message_name*
    _clone (::xml_schema::Flags f = 0,
            ::xml_schema::Container* c = 0) const;

    virtual 
    ~T_message_name ();
  };

  class T_method_name: public ::poosl::T_identifier
  {
    public:
    // Constructors.
    //
    T_method_name ();

    T_method_name (const char*);

    T_method_name (const ::std::string&);

    T_method_name (const ::xml_schema::String&);

    T_method_name (const ::xercesc::DOMElement& e,
                   ::xml_schema::Flags f = 0,
                   ::xml_schema::Container* c = 0);

    T_method_name (const ::xercesc::DOMAttr& a,
                   ::xml_schema::Flags f = 0,
                   ::xml_schema::Container* c = 0);

    T_method_name (const ::std::string& s,
                   const ::xercesc::DOMElement* e,
                   ::xml_schema::Flags f = 0,
                   ::xml_schema::Container* c = 0);

    T_method_name (const T_method_name& x,
                   ::xml_schema::Flags f = 0,
                   ::xml_schema::Container* c = 0);

    virtual T_method_name*
    _clone (::xml_schema::Flags f = 0,
            ::xml_schema::Container* c = 0) const;

    virtual 
    ~T_method_name ();
  };

  class T_data_method_name: public ::xml_schema::String
  {
    public:

    T_data_method_name ();

    T_data_method_name (const char* v);

    T_data_method_name (const ::std::string& v);

    T_data_method_name (const ::xercesc::DOMElement& e,
                        ::xml_schema::Flags f = 0,
                        ::xml_schema::Container* c = 0);

    T_data_method_name (const ::xercesc::DOMAttr& a,
                        ::xml_schema::Flags f = 0,
                        ::xml_schema::Container* c = 0);

    T_data_method_name (const ::std::string& s,
                        const ::xercesc::DOMElement* e,
                        ::xml_schema::Flags f = 0,
                        ::xml_schema::Container* c = 0);

    T_data_method_name (const T_data_method_name& x,
                        ::xml_schema::Flags f = 0,
                        ::xml_schema::Container* c = 0);

    virtual T_data_method_name*
    _clone (::xml_schema::Flags f = 0,
            ::xml_schema::Container* c = 0) const;
  };

  class T_operator: public ::xml_schema::String
  {
    public:
    // Constructors.
    //
    T_operator ();

    T_operator (const char*);

    T_operator (const ::std::string&);

    T_operator (const ::xml_schema::String&);

    T_operator (const ::xercesc::DOMElement& e,
                ::xml_schema::Flags f = 0,
                ::xml_schema::Container* c = 0);

    T_operator (const ::xercesc::DOMAttr& a,
                ::xml_schema::Flags f = 0,
                ::xml_schema::Container* c = 0);

    T_operator (const ::std::string& s,
                const ::xercesc::DOMElement* e,
                ::xml_schema::Flags f = 0,
                ::xml_schema::Container* c = 0);

    T_operator (const T_operator& x,
                ::xml_schema::Flags f = 0,
                ::xml_schema::Container* c = 0);

    virtual T_operator*
    _clone (::xml_schema::Flags f = 0,
            ::xml_schema::Container* c = 0) const;

    virtual 
    ~T_operator ();
  };

  class T_empty: public ::xml_schema::Type
  {
    public:
    // stmt_handle
    //
    typedef ::xml_schema::Int Stmt_handleType;
    typedef ::xsd::cxx::tree::optional< Stmt_handleType > Stmt_handleOptional;
    typedef ::xsd::cxx::tree::traits< Stmt_handleType, char > Stmt_handleTraits;

    const Stmt_handleOptional&
    getStmt_handle () const;

    Stmt_handleOptional&
    getStmt_handle ();

    void
    setStmt_handle (const Stmt_handleType& x);

    void
    setStmt_handle (const Stmt_handleOptional& x);

    // Constructors.
    //
    T_empty ();

    T_empty (const ::xercesc::DOMElement& e,
             ::xml_schema::Flags f = 0,
             ::xml_schema::Container* c = 0);

    T_empty (const T_empty& x,
             ::xml_schema::Flags f = 0,
             ::xml_schema::Container* c = 0);

    virtual T_empty*
    _clone (::xml_schema::Flags f = 0,
            ::xml_schema::Container* c = 0) const;

    T_empty&
    operator= (const T_empty& x);

    virtual 
    ~T_empty ();

    // Implementation.
    //
    protected:
    void
    parse (::xsd::cxx::xml::dom::parser< char >&,
           ::xml_schema::Flags);

    protected:
    Stmt_handleOptional stmt_handle_;
  };
}

#include <iosfwd>

namespace poosl
{
  ::std::ostream&
  operator<< (::std::ostream&, T_message_type::Value);

  ::std::ostream&
  operator<< (::std::ostream&, const T_message_type&);

  ::std::ostream&
  operator<< (::std::ostream&, T_boolean::Value);

  ::std::ostream&
  operator<< (::std::ostream&, const T_boolean&);

  ::std::ostream&
  operator<< (::std::ostream&, const T_typed_variable&);

  ::std::ostream&
  operator<< (::std::ostream&, const T_poosl_type_attribute&);

  ::std::ostream&
  operator<< (::std::ostream&, const T_identifier&);

  ::std::ostream&
  operator<< (::std::ostream&, const T_class_name&);

  ::std::ostream&
  operator<< (::std::ostream&, const T_poosl_type&);

  ::std::ostream&
  operator<< (::std::ostream&, const T_port_name&);

  ::std::ostream&
  operator<< (::std::ostream&, const T_variable_name&);

  ::std::ostream&
  operator<< (::std::ostream&, const T_message_name&);

  ::std::ostream&
  operator<< (::std::ostream&, const T_method_name&);

  ::std::ostream&
  operator<< (::std::ostream&, const T_data_method_name&);

  ::std::ostream&
  operator<< (::std::ostream&, const T_operator&);

  ::std::ostream&
  operator<< (::std::ostream&, const T_empty&);
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace poosl
{
}

#include <iosfwd>

#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>
#include <xercesc/framework/XMLFormatter.hpp>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

namespace poosl
{
  void
  operator<< (::xercesc::DOMElement&, const T_message_type&);

  void
  operator<< (::xercesc::DOMAttr&, const T_message_type&);

  void
  operator<< (::xml_schema::ListStream&,
              const T_message_type&);

  void
  operator<< (::xercesc::DOMElement&, const T_boolean&);

  void
  operator<< (::xercesc::DOMAttr&, const T_boolean&);

  void
  operator<< (::xml_schema::ListStream&,
              const T_boolean&);

  void
  operator<< (::xercesc::DOMElement&, const T_typed_variable&);

  void
  operator<< (::xercesc::DOMElement&, const T_poosl_type_attribute&);

  void
  operator<< (::xercesc::DOMElement&, const T_identifier&);

  void
  operator<< (::xercesc::DOMAttr&, const T_identifier&);

  void
  operator<< (::xml_schema::ListStream&,
              const T_identifier&);

  void
  operator<< (::xercesc::DOMElement&, const T_class_name&);

  void
  operator<< (::xercesc::DOMAttr&, const T_class_name&);

  void
  operator<< (::xml_schema::ListStream&,
              const T_class_name&);

  void
  operator<< (::xercesc::DOMElement&, const T_poosl_type&);

  void
  operator<< (::xercesc::DOMAttr&, const T_poosl_type&);

  void
  operator<< (::xml_schema::ListStream&,
              const T_poosl_type&);

  void
  operator<< (::xercesc::DOMElement&, const T_port_name&);

  void
  operator<< (::xercesc::DOMAttr&, const T_port_name&);

  void
  operator<< (::xml_schema::ListStream&,
              const T_port_name&);

  void
  operator<< (::xercesc::DOMElement&, const T_variable_name&);

  void
  operator<< (::xercesc::DOMAttr&, const T_variable_name&);

  void
  operator<< (::xml_schema::ListStream&,
              const T_variable_name&);

  void
  operator<< (::xercesc::DOMElement&, const T_message_name&);

  void
  operator<< (::xercesc::DOMAttr&, const T_message_name&);

  void
  operator<< (::xml_schema::ListStream&,
              const T_message_name&);

  void
  operator<< (::xercesc::DOMElement&, const T_method_name&);

  void
  operator<< (::xercesc::DOMAttr&, const T_method_name&);

  void
  operator<< (::xml_schema::ListStream&,
              const T_method_name&);

  void
  operator<< (::xercesc::DOMElement&, const T_data_method_name&);

  void
  operator<< (::xercesc::DOMAttr&, const T_data_method_name&);

  void
  operator<< (::xml_schema::ListStream&,
              const T_data_method_name&);

  void
  operator<< (::xercesc::DOMElement&, const T_operator&);

  void
  operator<< (::xercesc::DOMAttr&, const T_operator&);

  void
  operator<< (::xml_schema::ListStream&,
              const T_operator&);

  void
  operator<< (::xercesc::DOMElement&, const T_empty&);
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // POOSLTYPES_HXX
